---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Apply tuned profile 
  shell: tuned-adm profile latency-performance

- name: Delete existing benchmark directory
  file: path=/opt/benchmark state=absent

- name: Copy benchmark code
  unarchive:
    src: ../../../package/target/openmessaging-benchmark-0.0.1-SNAPSHOT-bin.tar.gz
    dest: /opt

- name: Rename benchmark directory
  shell: mv /opt/openmessaging-benchmark-0.0.1-SNAPSHOT /opt/benchmark

- name: Get list of driver config files
  raw: ls -1 /opt/benchmark/driver-kafka/*.yaml
  register: drivers_list

- name: Configure Bootstrap Servers
  lineinfile:
      dest: '{{ item }}'
      regexp: '^  bootstrap.servers='
      line: '  bootstrap.servers={{ bootstrapServers }}'
  with_items: '{{ drivers_list.stdout_lines }}'

- name: Get list of jms driver config files
  raw: ls -1 /opt/benchmark/driver-jms/kafka*.yaml
  register: jms_drivers_list

- name: Configure JMS Bootstrap Servers
  lineinfile:
      dest: '{{ item }}'
      regexp: '^  bootstrap.servers='
      line: '  bootstrap.servers={{ bootstrapServers }}'
  with_items: '{{ jms_drivers_list.stdout_lines }}'

- name: Configure JMS Connection Factory
  ansible.builtin.replace:
      dest: '{{ item }}'
      regexp: 'localhost\:9092'
      replace: '{{ bootstrapServers }}'
  with_items: '{{ jms_drivers_list.stdout_lines }}'

- name: Configure benchmark worker memory
  lineinfile:
      dest: /opt/benchmark/bin/benchmark-worker
      regexp: '^JVM_MEM='
      line: 'JVM_MEM="-Xms100G -Xmx100G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+ParallelRefProcEnabled -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=12 -XX:ConcGCThreads=12 -XX:+DisableExplicitGC -XX:-ResizePLAB"'

- name: Configure benchmark memory
  lineinfile:
      dest: /opt/benchmark/bin/benchmark
      regexp: '^JVM_MEM='
      line: 'JVM_MEM="-Xmx4G"'

- name: Generate benchmark worker 
  template:
    src: "templates/workers.yaml"
    dest: "/opt/benchmark/workers.yaml"

- name: Install benchmark systemd service
  copy:
    src: "benchmark-worker.service"
    dest: "/etc/systemd/system/benchmark-worker.service"

- systemd:
    state: restarted
    daemon_reload: yes
    name: "benchmark-worker"
